=== ChristianMeisenbichler/exciting/xml/species.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
    <xs:annotation>
    	<xs:documentation>
      This document describes the file format for the species definitions.</xs:documentation>
<xs:appinfo>
<title>Species file format reference</title>
<root>spdb</root> 
</xs:appinfo>
</xs:annotation>
<xs:simpleType name="fortrandouble">
<xs:annotation>
  <xs:documentation> The type <pre>fortrandouble</pre> allows to use the letters
        <pre>"eEdDqQ"</pre> for exponent operators. This alters in what precision the number is
        parsed. </xs:documentation>
        </xs:annotation>
  <xs:restriction base="xs:token">
    <xs:pattern value="[-]?[0-9]*\.?[0-9]+([eEdDqQ][-+]?[0-9]+)?"/>
  </xs:restriction>
</xs:simpleType>
    <xs:element name="wf" >
        <xs:annotation>
        	<xs:documentation>Defines the radial part of an  atomic wavefunction. This functions used to construct a lapw orbital. 
          The actual basis functions  for the calculation inside the MT are linear combinations of these and <inlinemath>Y_{lm}</inlinemath>.</xs:documentation>
        </xs:annotation>
        
        <xs:complexType>
    		
            <xs:attribute name="trialEnergy" type="fortrandouble" use="required">
    			<xs:annotation>
    				<xs:documentation>Energy level of the radial wave function (initial condition for numerical radial Schrodinger equation)</xs:documentation>
    			</xs:annotation></xs:attribute>
            
            <xs:attribute name="matchingOrder" type="xs:integer" use="required">
            <xs:annotation>
            <xs:documentation>
            Gives the order of the derivative that must be matched to the plain wave.
            </xs:documentation>
            </xs:annotation>
            </xs:attribute>
            
            <xs:attribute name="searchE" type="xs:boolean" use="required">
    			<xs:annotation>
    				<xs:documentation>If <pre>true</pre> the energy of the radial wave function,
            <inlinemath>E_0</inlinemath> is optimized to match the boundary condition 
            
            <displaymath>\psi(R_{MT})=0.</displaymath></xs:documentation>
    			</xs:annotation></xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="sp">
    	
    
        <xs:annotation>
    		<xs:documentation>A species is an atom type definition containing all information to construct the basis functions.</xs:documentation>
    	</xs:annotation>
        
        <xs:complexType>
    	
            <xs:sequence>
    		
                <xs:element name="muffinTin" minOccurs="1" maxOccurs="1">
                
                    <xs:annotation>
                	<xs:documentation>This element gives the size of the muffin tin radius and 
                  the resolution of the radial functions. </xs:documentation>
                </xs:annotation>
                     
                    <xs:complexType>
    				
                        <xs:attribute name="rmin" type="fortrandouble" use="required">
                          <xs:annotation>
                            <xs:documentation>The radius where radial mesh begins.</xs:documentation>
                          </xs:annotation></xs:attribute>
                        
                        <xs:attribute name="rinf" type="fortrandouble" use="required">
                         <xs:annotation>
                            <xs:documentation>Radius from which the influence on the potential is regarded to be negligible.</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        
                        <xs:attribute name="radius" type="fortrandouble" use="required">
                         <xs:annotation>
                            <xs:documentation>The radius of the muffin tin sphere.</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        
                        <xs:attribute name="radialmeshPoints" type="xs:integer" use="required">
                          <xs:annotation>
                            <xs:documentation>Number of data points for radial atomic functions.</xs:documentation>
                          </xs:annotation></xs:attribute>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="atomicState" minOccurs="1" maxOccurs="unbounded">
    			
                    <xs:annotation>
                      <xs:documentation>The <elementref>atomicState</elementref> element lists the atomic states that schould be used to approximate the wavefunction in the sphere. 
They can be marked as core or none core electrons by the <attref>core</attref> attribute. Core electrons are threated separately by numeric itegration.
</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
    				
                        <xs:attribute name="n" type="xs:integer" use="required">
                        <xs:annotation>
                        <xs:documentation>
                        Principal quantum number.
                        </xs:documentation>
                        </xs:annotation>
                        </xs:attribute>
                        
                        <xs:attribute name="l" type="xs:integer" use="required">
                        <xs:annotation>
                        <xs:documentation>
                        Azimuthal quantum number.
                        </xs:documentation>
                        </xs:annotation>
                        </xs:attribute>
                        
                        <xs:attribute name="kappa" type="xs:integer" use="required">
                   
                        <xs:annotation>
                        <xs:documentation>
                        Relativistic quantum number.
                        </xs:documentation>
                        </xs:annotation>
                        </xs:attribute>
                   
                        
                        <xs:attribute name="occ" type="fortrandouble" use="required">
                         <xs:annotation>
                        <xs:documentation>
                       Ocuppation number.
                        </xs:documentation>
                        </xs:annotation>
                        </xs:attribute>
                        
                        <xs:attribute name="core" type="xs:boolean" use="required">
                          <xs:annotation>
                        <xs:documentation>
                        If <pre>true</pre>, state is threated as core state in the calculation.
                        </xs:documentation>
                        </xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                

                <xs:element name="basis" minOccurs="1" maxOccurs="1">
                
                    <xs:annotation>
                	<xs:documentation>Defines APW basis.</xs:documentation>
                </xs:annotation>
                    
                    <xs:complexType>
    				
                        <xs:sequence>
    					
                            <xs:element ref="wf" maxOccurs="unbounded" minOccurs="1" />
                            
                            <xs:element name="exception" minOccurs="0" maxOccurs="unbounded">
                            <xs:annotation>
                            <xs:documentation>
                            This element allows for defining exceptions to the APW basis functions.
                            </xs:documentation>
                            </xs:annotation>						
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="wf" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                            
                                    <xs:attribute name="l" type="xs:integer">
                                    <xs:annotation>
                                    <xs:documentation>
                                    Spezifies the azimuthal quantum number for which the exception applies.
                                    
                                    </xs:documentation>
                                    </xs:annotation>
                                    </xs:attribute>
                                   
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        
                        <xs:attribute name="order" type="xs:integer" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="lorb" maxOccurs="unbounded" minOccurs="0">
                
                    <xs:annotation>
                	<xs:documentation>Local orbital (APW+lo or LAPW+lo).</xs:documentation>
                </xs:annotation>
                    
                    <xs:complexType>
    				
                        <xs:sequence>
    					
                            <xs:element ref="wf" minOccurs="1" maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                        
                        <xs:attribute name="l" type="xs:integer" use="required">
                        <xs:annotation>
                        <xs:documentation>
                        Azimuthal quantum number for which the local orbital is defined.
                        
                        </xs:documentation>
                        </xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            
            <xs:attribute name="chemicalSymbol" type="xs:ID" use="required">
    		<xs:annotation>
    		  <xs:documentation>Chemical Symbol.</xs:documentation>
    		</xs:annotation></xs:attribute>
            
            <xs:attribute name="z" type="fortrandouble" use="required">
    		<xs:annotation>
    		  <xs:documentation>Atomic number.</xs:documentation>
    		</xs:annotation></xs:attribute>
            
            <xs:attribute name="mass" type="fortrandouble" use="required">
    		<xs:annotation>
    		  <xs:documentation>Mass in <inlinemath>m_e</inlinemath>.</xs:documentation>
    		</xs:annotation></xs:attribute>
            
            <xs:attribute name="name" type="xs:string" use="optional">
    		<xs:annotation>
    		  <xs:documentation>Optional element name.</xs:documentation>
    		</xs:annotation></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="spdb">
           <xs:annotation>
        	<xs:documentation>Species-database element contains the species element <elementref>sp</elementref></xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="sp" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ChristianMeisenbichler/exciting/species/Rn.xml
<?xml version="1.0" encoding="UTF-8"?>
<spdb xsi:noNamespaceSchemaLocation="../../xml/species.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <sp chemicalSymbol="Rn" name="radon" z="-86.0000" mass="404681.2437">
    <muffinTin rmin="2.1566554640687682E-7" radius="2." rinf="29.10040558905078" radialmeshPoints="700"/>
    <atomicState n="1" l="0" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="2" l="0" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="2" l="1" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="2" l="1" kappa="2" occ="4.00000" core="true"/>
    <atomicState n="3" l="0" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="3" l="1" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="3" l="1" kappa="2" occ="4.00000" core="true"/>
    <atomicState n="3" l="2" kappa="2" occ="4.00000" core="true"/>
    <atomicState n="3" l="2" kappa="3" occ="6.00000" core="true"/>
    <atomicState n="4" l="0" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="4" l="1" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="4" l="1" kappa="2" occ="4.00000" core="true"/>
    <atomicState n="4" l="2" kappa="2" occ="4.00000" core="true"/>
    <atomicState n="4" l="2" kappa="3" occ="6.00000" core="true"/>
    <atomicState n="4" l="3" kappa="3" occ="6.00000" core="true"/>
    <atomicState n="4" l="3" kappa="4" occ="8.00000" core="true"/>
    <atomicState n="5" l="0" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="5" l="1" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="5" l="1" kappa="2" occ="4.00000" core="true"/>
    <atomicState n="5" l="2" kappa="2" occ="4.00000" core="false"/>
    <atomicState n="5" l="2" kappa="3" occ="6.00000" core="false"/>
    <atomicState n="6" l="0" kappa="1" occ="2.00000" core="false"/>
    <atomicState n="6" l="1" kappa="1" occ="2.00000" core="false"/>
    <atomicState n="6" l="1" kappa="2" occ="4.00000" core="false"/>
    <basis order="1">
      <wf matchingOrder="0" trialEnergy="0.15" searchE="false"/>
      <exception l="0">
        <wf matchingOrder="0" trialEnergy="0.15" searchE="true"/>
      </exception>
      <exception l="1">
        <wf matchingOrder="0" trialEnergy="0.15" searchE="true"/>
      </exception>
      <exception l="2">
        <wf matchingOrder="0" trialEnergy="0.15" searchE="true"/>
      </exception>
      <exception l="3">
        <wf matchingOrder="0" trialEnergy="0.15" searchE="true"/>
      </exception>
    </basis>
    <lorb l="0">
      <wf matchingOrder="0" trialEnergy="0.15" searchE="true"/>
      <wf matchingOrder="1" trialEnergy="0.15" searchE="true"/>
    </lorb>
    <lorb l="1">
      <wf matchingOrder="0" trialEnergy="0.15" searchE="true"/>
      <wf matchingOrder="1" trialEnergy="0.15" searchE="true"/>
    </lorb>
    <lorb l="2">
      <wf matchingOrder="0" trialEnergy="0.15" searchE="true"/>
      <wf matchingOrder="1" trialEnergy="0.15" searchE="true"/>
    </lorb>
    <lorb l="3">
      <wf matchingOrder="0" trialEnergy="0.15" searchE="true"/>
      <wf matchingOrder="1" trialEnergy="0.15" searchE="true"/>
    </lorb>
    <lorb l="2">
      <wf matchingOrder="0" trialEnergy="0.15" searchE="false"/>
      <wf matchingOrder="1" trialEnergy="0.15" searchE="false"/>
      <wf matchingOrder="0" trialEnergy="-1.7155383331273355" searchE="true"/>
    </lorb>
    <lorb l="0">
      <wf matchingOrder="0" trialEnergy="0.15" searchE="false"/>
      <wf matchingOrder="1" trialEnergy="0.15" searchE="false"/>
      <wf matchingOrder="0" trialEnergy="-0.7334685627369997" searchE="true"/>
    </lorb>
    <lorb l="1">
      <wf matchingOrder="0" trialEnergy="0.15" searchE="false"/>
      <wf matchingOrder="1" trialEnergy="0.15" searchE="false"/>
      <wf matchingOrder="0" trialEnergy="-0.3136413291292162" searchE="true"/>
    </lorb>
    <!-- Exciting code version : 0.9.224-->
    <!-- Description of  method-->
    <!--APW+lo-->
  </sp>
</spdb>

=== ChristianMeisenbichler/exciting/species/Zn_APWloLegacy.xml
<?xml version="1.0" encoding="UTF-8"?>
<spdb xsi:noNamespaceSchemaLocation="../../xml/species.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <sp chemicalSymbol="Zn" name="zinc" z="-30.0000" mass="119198.6780">
    <muffinTin rmin="0.365148E-06" radius="2.0000" rinf="31.8739" radialmeshPoints="500"/>
    <atomicState n="1" l="0" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="2" l="0" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="2" l="1" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="2" l="1" kappa="2" occ="4.00000" core="true"/>
    <atomicState n="3" l="0" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="3" l="1" kappa="1" occ="2.00000" core="false"/>
    <atomicState n="3" l="1" kappa="2" occ="4.00000" core="false"/>
    <atomicState n="3" l="2" kappa="2" occ="4.00000" core="false"/>
    <atomicState n="3" l="2" kappa="3" occ="6.00000" core="false"/>
    <atomicState n="4" l="0" kappa="1" occ="2.00000" core="false"/>
    <basis order="1">
      <wf matchingOrder="0" trialEnergy="0.1500" searchE="false"/>
    </basis>
    <lorb l="0">
      <wf matchingOrder="0" trialEnergy="0.1500" searchE="false"/>
      <wf matchingOrder="1" trialEnergy="0.1500" searchE="false"/>
    </lorb>
    <lorb l="1">
      <wf matchingOrder="0" trialEnergy="0.1500" searchE="false"/>
      <wf matchingOrder="1" trialEnergy="0.1500" searchE="false"/>
    </lorb>
    <lorb l="2">
      <wf matchingOrder="0" trialEnergy="0.1500" searchE="false"/>
      <wf matchingOrder="1" trialEnergy="0.1500" searchE="false"/>
    </lorb>
    <lorb l="3">
      <wf matchingOrder="0" trialEnergy="0.1500" searchE="false"/>
      <wf matchingOrder="1" trialEnergy="0.1500" searchE="false"/>
    </lorb>
    <lorb l="1">
      <wf matchingOrder="0" trialEnergy="0.1500" searchE="false"/>
      <wf matchingOrder="1" trialEnergy="0.1500" searchE="false"/>
      <wf matchingOrder="0" trialEnergy="-3.0602" searchE="true"/>
    </lorb>
    <lorb l="2">
      <wf matchingOrder="0" trialEnergy="0.1500" searchE="false"/>
      <wf matchingOrder="1" trialEnergy="0.1500" searchE="false"/>
      <wf matchingOrder="0" trialEnergy="-0.3160" searchE="true"/>
    </lorb>
    <!-- Exciting code version : 0.9.224-->
    <!-- Description of method:-->
    <!-- APW+lo-Legacy -->
  </sp>
</spdb>

=== ChristianMeisenbichler/exciting/species/Si_SLAPW3.xml
<?xml version="1.0" encoding="UTF-8"?>
<spdb xsi:noNamespaceSchemaLocation="../../xml/species.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <sp chemicalSymbol="Si" name="silicon" z="-14.0000" mass="51196.73454">
    <muffinTin rmin="0.534522E-06" radius="2.0000" rinf="39.5679" radialmeshPoints="400"/>
    <atomicState n="1" l="0" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="2" l="0" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="2" l="1" kappa="1" occ="2.00000" core="true"/>
    <atomicState n="2" l="1" kappa="2" occ="4.00000" core="true"/>
    <atomicState n="3" l="0" kappa="1" occ="2.00000" core="false"/>
    <atomicState n="3" l="1" kappa="1" occ="1.00000" core="false"/>
    <atomicState n="3" l="1" kappa="2" occ="1.00000" core="false"/>
    <basis order="2">
      <wf matchingOrder="0" trialEnergy="0.1500" searchE="false"/>
      <wf matchingOrder="1" trialEnergy="0.1500" searchE="false"/>
      <exception l="0">
        <wf matchingOrder="0" trialEnergy="0.1500" searchE="false"/>
        <wf matchingOrder="0" trialEnergy="0.1500" searchE="false"/>
        <wf matchingOrder="0" trialEnergy="0.1500" searchE="true"/>
      </exception>
      <exception l="1">
        <wf matchingOrder="0" trialEnergy="0.1500" searchE="false"/>
        <wf matchingOrder="0" trialEnergy="0.1500" searchE="false"/>
        <wf matchingOrder="0" trialEnergy="0.1500" searchE="true"/>
      </exception>
      <exception l="2">
        <wf matchingOrder="0" trialEnergy="0.1500" searchE="false"/>
        <wf matchingOrder="0" trialEnergy="0.1500" searchE="false"/>
        <wf matchingOrder="0" trialEnergy="0.1500" searchE="true"/>
      </exception>
    </basis>
    <!-- Exciting code version : 0.9.224-->
    <!-- Description of method:-->
    <!-- SLAPW-3 (experimental) -->
  </sp>
</spdb>
